
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND CHARACTER COMMA DIVIDE ELSE EQ EQUAL FLOAT FOR GE GT ID IDTYPE IF INTEGER LAND LBRACE LBRACKET LE LNOT LOR LPAREN LSHIFT LT MINUS MODULO NE NOT OR PERIOD PLUS RBRACE RBRACKET RPAREN RSHIFT SEMI STRING TIMES WHILE XORall_sentences : list_sentences sentencelist_sentences : sentencesentence : declaration\n                | assigndeclaration : IDTYPE ID SEMItvariable : STRING\n                 | ID\n                 | INTEGER\n                 | FLOAT\n                 | CHARACTERassign : IDTYPE ID EQUAL tvariable SEMI'
    
_lr_action_items = {'IDTYPE':([0,2,3,4,5,9,17,],[6,6,-2,-3,-4,-5,-11,]),'$end':([1,4,5,7,9,17,],[0,-3,-4,-1,-5,-11,]),'ID':([6,10,],[8,11,]),'SEMI':([8,11,12,13,14,15,16,],[9,-7,17,-6,-8,-9,-10,]),'EQUAL':([8,],[10,]),'STRING':([10,],[13,]),'INTEGER':([10,],[14,]),'FLOAT':([10,],[15,]),'CHARACTER':([10,],[16,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'all_sentences':([0,],[1,]),'list_sentences':([0,],[2,]),'sentence':([0,2,],[3,7,]),'declaration':([0,2,],[4,4,]),'assign':([0,2,],[5,5,]),'tvariable':([10,],[12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> all_sentences","S'",1,None,None,None),
  ('all_sentences -> list_sentences sentence','all_sentences',2,'p_all_sentences','parser.py',16),
  ('list_sentences -> sentence','list_sentences',1,'p_list_sentences','parser.py',20),
  ('sentence -> declaration','sentence',1,'p_sentence','parser.py',24),
  ('sentence -> assign','sentence',1,'p_sentence','parser.py',25),
  ('declaration -> IDTYPE ID SEMI','declaration',3,'p_declaration','parser.py',30),
  ('tvariable -> STRING','tvariable',1,'p_tvariable','parser.py',34),
  ('tvariable -> ID','tvariable',1,'p_tvariable','parser.py',35),
  ('tvariable -> INTEGER','tvariable',1,'p_tvariable','parser.py',36),
  ('tvariable -> FLOAT','tvariable',1,'p_tvariable','parser.py',37),
  ('tvariable -> CHARACTER','tvariable',1,'p_tvariable','parser.py',38),
  ('assign -> IDTYPE ID EQUAL tvariable SEMI','assign',5,'p_assign','parser.py',41),
]
